In [3]:
import numpy as np

marks = np.array([
[85, 78, 92, 88],
[74, 81, 69, 72],
[90, 95, 88, 91],
[70, 75, 80, 75],
[88, 84, 86, 86],
[65, 72, 74, 82],
[91, 89, 87, 83],
[68, 70, 72, 87],
[84, 86, 85, 87],
[72, 76, 78, 77]
])
subjects = ["Math", "Science", "Chemistry", "Computer Science"]
#add 3 marks to each student in math
marks[:, 2] += 3
# Calculate the average marks for each student
average_marks = np.mean(marks, axis=1)
# Calculate the average marks for each subject
average_subject_marks = np.mean(marks, axis=0)
# highest marks in class
highest_marks = np.max(marks)
# lowest marks in class
lowest_marks = np.min(marks)
#students where average marks is above 80
students_above_80 = np.where(average_marks > 80)[0]
#hardest subject (lowest average marks)
hardest_subject_index = np.argmin(average_subject_marks)
hardest_subject = subjects[hardest_subject_index]
#easiest subject (highest average marks)
easiest_subject_index = np.argmax(average_subject_marks)
easiest_subject = subjects[easiest_subject_index]
# top 3 students based on average marks
top_students_indices = np.argsort(average_marks)[-3:][::-1]
print("Average marks for each student:", average_marks)
print("Average marks for each subject:", average_subject_marks)
print("Highest marks in class:", highest_marks)
print("Lowest marks in class:", lowest_marks)
print("Students above 80:", students_above_80 + 1)
print("Total:", len(students_above_80))
print("Hardest subject:", hardest_subject)
print("Easiest subject:", easiest_subject)
print("Top 3 students based on average marks:", top_students_indices + 1)  # Adding 1 to convert from index to student number

Average marks for each student: [86.5  74.75 91.75 75.75 86.75 74.   88.25 75.   86.25 76.5 ]
Average marks for each subject: [78.7 80.6 84.1 82.8]
Highest marks in class: 95
Lowest marks in class: 65
Students above 80: [1 3 5 7 9]
Total: 5
Hardest subject: Math
Easiest subject: Chemistry
Top 3 students based on average marks: [3 7 5]


In [4]:
import numpy as np

A = np.array([
[10,20,30],
[40,50,60],
[70,80,90]
])
print("2nd row of A:", A[1])
print("3rd column of A:", A[:, 2])
print("element 50:", A[1, 1])
print("first two columns of A:", A[:, :2])
A5=A+5
print("A+5:", A5)
# add [1,2,3] to each row of A
A_plus_row = A + np.array([1, 2, 3])
print("A + [1, 2, 3]:", A_plus_row)
# add 5 to column 1 of A
A_plus_col = A + np.array([[0], [5], [0]])
print("A + 5 to column 1:", A_plus_col)
A[:, 1] = A[:, 1] + 5
print("A with 5 added to column 1:", A)

2nd row of A: [40 50 60]
3rd column of A: [30 60 90]
element 50: 50
first two columns of A: [[10 20]
 [40 50]
 [70 80]]
A+5: [[15 25 35]
 [45 55 65]
 [75 85 95]]
A + [1, 2, 3]: [[11 22 33]
 [41 52 63]
 [71 82 93]]
A + 5 to column 1: [[10 20 30]
 [45 55 65]
 [70 80 90]]
A with 5 added to column 1: [[10 25 30]
 [40 55 60]
 [70 85 90]]


In [5]:
import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
# 2nd row of A
second_row = A[1]
print("2nd row of A:", second_row)
# 3rd column of A
third_column = A[:, 2]
print("3rd column of A:", third_column)
# element at position (2, 0)
elements=A[2,0]
print("Element at position (2, 0):", elements)
# first two columns of A
first_two_columns = A[:, :2]
print("First two columns of A:", first_two_columns)
# add 10 to each element of A
A_plus_10 = A + 10
print("A + 10:", A_plus_10)
# add [1, 2, 3] to each row of A
A_plus_row = A + np.array([1, 2, 3])
print("A + [1, 2, 3]:", A_plus_row)
# multiply column 2 of A by 3
A_mult_col2 = A[:, 1] * 3
print("A[:, 1] * 3:", A_mult_col2)


2nd row of A: [4 5 6]
3rd column of A: [3 6 9]
Element at position (2, 0): 7
First two columns of A: [[1 2]
 [4 5]
 [7 8]]
A + 10: [[11 12 13]
 [14 15 16]
 [17 18 19]]
A + [1, 2, 3]: [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
A[:, 1] * 3: [ 6 15 24]


In [6]:
B = np.array([
    [5, 10, 15],
    [20, 25, 30],
    [35, 40, 45],
    [50, 55, 60]
])
# last row of B
last_row = B[-1]
print("Last row of B:", last_row)
#first 2 rows of B
first_two_rows = B[:2]
print("First 2 rows of B:", first_two_rows)
# all rows,2nd column of B
second_column = B[:, 1]
print("All rows, 2nd column of B:", second_column)
# add row [1, 2, 3] to each row of B
B_plus_row = B + np.array([1, 2, 3])
print("B + [1, 2, 3]:", B_plus_row) 
# subtract 5 from all elements in column 3 of B
B_minus_col3 = B.copy()
B_minus_col3[:, 2] -= 5
print("B - 5 from column 3:", B_minus_col3) 
# multiply column 1 of B by 2
B_mult_col1 = B[:, 0] * 2
print("B[:, 0] * 2:", B_mult_col1)

Last row of B: [50 55 60]
First 2 rows of B: [[ 5 10 15]
 [20 25 30]]
All rows, 2nd column of B: [10 25 40 55]
B + [1, 2, 3]: [[ 6 12 18]
 [21 27 33]
 [36 42 48]
 [51 57 63]]
B - 5 from column 3: [[ 5 10 10]
 [20 25 25]
 [35 40 40]
 [50 55 55]]
B[:, 0] * 2: [ 10  40  70 100]


In [7]:
C = np.array([
    [0.5, 1.0, 1.5],
    [2.0, 2.5, 3.0],
    [3.5, 4.0, 4.5]
])
# sum of each row of C
row_sums = np.sum(C, axis=1)
print("Sum of each row of C:", row_sums)
# mean of each column of C
column_means = np.mean(C, axis=0)
print("Mean of each column of C:", column_means)
#flatten C into 1D array
flattened_C = C.flatten()
print("Flattened C:", flattened_C)
# C by 2
C_times_2 = C * 2
print("C * 2:", C_times_2)
# add [0.1,0.2,0.3] to each row of C
C_plus_row = C + np.array([0.1, 0.2, 0.3])
print("C + [0.1, 0.2, 0.3]:", C_plus_row)

Sum of each row of C: [ 3.   7.5 12. ]
Mean of each column of C: [2.  2.5 3. ]
Flattened C: [0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
C * 2: [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
C + [0.1, 0.2, 0.3]: [[0.6 1.2 1.8]
 [2.1 2.7 3.3]
 [3.6 4.2 4.8]]


In [8]:
import numpy as np

# Dataset
D = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120],
    [130, 140, 150, 160]
])
#3rd row of D
third_row = D[2]
print("1.3rd row of D:", third_row)
#2nd column of D
second_column = D[:, 1]
print("2.2nd column of D:", second_column)
# element at position (4, 3)
element = D[3, 2]
print("3. Element at position (4, 3):", element)
# first 2 rows and last 2 columns of D
subset = D[:2, 2:]
print("4. First 2 rows and last 2 columns of D:", subset)
# add [1,2,3,4] to each row of D
D_plus_row = D + np.array([1, 2, 3, 4])
print("5. D + [1, 2, 3, 4]:", D_plus_row)
# subtract 10 from all elements in column 3 of D
D_minus_column = D[:, 2] - 10
print("6. D - 10 (column 3):", D_minus_column) 
# multiply column 1 of D by 3
D_mult_column = D[:, 0] * 3
print("7. D[:, 0] * 3:", D_mult_column)
# sum of each column of D
column_sums = np.sum(D, axis=0)
print("8. Sum of each column of D:", column_sums)
# mean of each row of D
row_means = np.mean(D, axis=1)
print("9. Mean of each row of D:", row_means)
# flatten D into 1D np.array
flattened_D = D.flatten()
print("10. Flattened D:", flattened_D)
# all elememts greater than 100 in D
greater_than_100 = D[D > 100]
print("11. Elements greater than 100 in D:", greater_than_100)
#Slice every other row and every other column of D
sliced_D = D[::2, ::2]
print("12. Every other row and every other column of D:", sliced_D)

1.3rd row of D: [ 90 100 110 120]
2.2nd column of D: [ 20  60 100 140]
3. Element at position (4, 3): 150
4. First 2 rows and last 2 columns of D: [[30 40]
 [70 80]]
5. D + [1, 2, 3, 4]: [[ 11  22  33  44]
 [ 51  62  73  84]
 [ 91 102 113 124]
 [131 142 153 164]]
6. D - 10 (column 3): [ 20  60 100 140]
7. D[:, 0] * 3: [ 30 150 270 390]
8. Sum of each column of D: [280 320 360 400]
9. Mean of each row of D: [ 25.  65. 105. 145.]
10. Flattened D: [ 10  20  30  40  50  60  70  80  90 100 110 120 130 140 150 160]
11. Elements greater than 100 in D: [110 120 130 140 150 160]
12. Every other row and every other column of D: [[ 10  30]
 [ 90 110]]


In [ ]:
import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
# elements greater than 5 in A
greater_than_5 = A[A > 5] 
print("Elements greater than 5 in A:", greater_than_5)
# mean of axis 0 of A
mean_axis_0 = np.mean(A, axis=0)
print("Mean of axis 0 of A:", mean_axis_0)
#normalize A by subtracting mean and dividing by std deviation
max_A = np.max(A)
min_A = np.min(A)
normalized_A = (A - min_A) / (max_A - min_A) 
print("Normalized A:", normalized_A)
# A multiplied by its transpose
A_transpose = A.T
A_mult_transpose = np.dot(A, A_transpose)
print("A multiplied by its transpose:", A_mult_transpose)


Elements greater than 5 in A: [6 7 8 9]
Mean of axis 0 of A: [4. 5. 6.]
Normalized A: [[-1.    -0.875 -0.75 ]
 [-0.625 -0.5   -0.375]
 [-0.25  -0.125  0.   ]]
A multiplied by its transpose: [[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]
